# -*- coding: utf-8 -*-
"""Produtividade com redes neurais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2e5-dZ-aMh_Jg4NWc1RXojymD5oXSW8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input

import warnings
warnings.filterwarnings('ignore')

# 1 - CARREGAR O DATASET

print("Faça o upload do arquivo CSV:")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)
print("\nDataset carregado!")
df

# 2 - SELECIONAR OS ATRIBUTOS

X = df[['Precipitacao', 'Temp_Max', 'Temp_Min', 'Umidade', 'Temp_Media', 'Ano', 'Mes']]
y = df['Producao_t']


# 3 - NORMALIZAÇÃO

mms_X = MinMaxScaler()
mms_y = MinMaxScaler()

X = mms_X.fit_transform(X)
y = mms_y.fit_transform(y.values.reshape(-1, 1)).flatten()

# 4 - SEPARAR TREINO E TESTE

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nTreino: {len(X_train)} amostras")
print(f"Teste: {len(X_test)} amostras")

# 5 - PREPARAR O MODELO (MLP)

mlp = Sequential()

mlp.add(Input(shape=(7,)))
mlp.add(Dense(16, activation='relu'))
mlp.add(Dense(8, activation='relu'))
mlp.add(Dense(1, activation='linear'))

mlp.compile(loss='mse', optimizer='adam')

# 6 - TREINAR O MODELO

epochs = int(input("\nQuantos treinamentos (epochs)? "))

print(f"\nTreinando a rede neural ({epochs} epochs)...\n")
mlp.fit(X_train, y_train, epochs=epochs, verbose=1)

print("\nModelo treinado!")

# 7 - PREVISÃO PARA ANOS FUTUROS

ano_futuro = int(input("\nQual ano deseja prever? (ex: 2025): "))

# Médias climáticas por mês (histórico)
medias = df.groupby('Mes').agg({
    'Precipitacao': 'mean',
    'Temp_Max': 'mean',
    'Temp_Min': 'mean',
    'Umidade': 'mean',
    'Temp_Media': 'mean'
}).reset_index()

# Criar dados do ano futuro
dados_futuro = []
for _, row in medias.iterrows():
    dados_futuro.append([
        row['Precipitacao'],
        row['Temp_Max'],
        row['Temp_Min'],
        row['Umidade'],
        row['Temp_Media'],
        ano_futuro,
        row['Mes']
    ])

X_futuro = np.array(dados_futuro)
X_futuro_norm = mms_X.transform(X_futuro)

# Previsão
y_futuro_norm = mlp.predict(X_futuro_norm, verbose=0).flatten()
y_futuro = mms_y.inverse_transform(y_futuro_norm.reshape(-1, 1)).flatten()

# 8 - TABELA: PREVISÃO DE DADOS CLIMÁTICOS

print("\n" + "=" * 50)
print(f"TABELA 1: PREVISÃO DE DADOS CLIMÁTICOS ({ano_futuro})")
print("=" * 50)

tabela_clima = pd.DataFrame({
    'Mês': medias['Mes'].astype(int),
    'Precipitação (mm)': medias['Precipitacao'].round(2),
    'Temp. Máx (°C)': medias['Temp_Max'].round(2),
    'Temp. Mín (°C)': medias['Temp_Min'].round(2),
    'Umidade (%)': medias['Umidade'].round(2),
    'Temp. Média (°C)': medias['Temp_Media'].round(2)
})
display(tabela_clima)

# 9 - TABELA: PREVISÃO DE PRODUTIVIDADE

print("\n" + "=" * 50)
print(f"TABELA 2: PREVISÃO DE PRODUTIVIDADE ({ano_futuro})")
print("=" * 50)

tabela_prod = pd.DataFrame({
    'Mês': list(range(1, 13)),
    'Produtividade Prevista (t)': y_futuro.round(2)
})
display(tabela_prod)

print(f"\nProdução Total Prevista {ano_futuro}: {y_futuro.sum():.2f} toneladas")

# 10 - GRÁFICO 1: PRODUTIVIDADE HISTÓRICA (2018-2024)

print("\n" + "=" * 50)
print("GRÁFICO 1: PRODUTIVIDADE HISTÓRICA (2018-2024)")
print("=" * 50)

historico = df.groupby('Ano')['Producao_t'].sum()

plt.figure(figsize=(10, 6))
plt.bar(historico.index.astype(int), historico.values, color='#3498db', edgecolor='black')
plt.xlabel('Ano', fontsize=12)
plt.ylabel('Produção Total (t)', fontsize=12)
plt.title('Produtividade Histórica (2018-2024)', fontsize=14, fontweight='bold')
plt.xticks(historico.index.astype(int))
for i, v in enumerate(historico.values):
    plt.text(historico.index[i], v + max(historico.values)*0.02, f'{v:.0f}',
             ha='center', fontsize=10, fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('grafico_historico.png', dpi=300)
plt.show()

print(" Gráfico salvo: 'grafico_historico.png'")

# 11 - GRÁFICO 2: PREVISÃO DO ANO SOLICITADO

print("\n" + "=" * 50)
print(f"GRÁFICO 2: PREVISÃO DE PRODUTIVIDADE ({ano_futuro})")
print("=" * 50)

meses = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun',
         'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']

plt.figure(figsize=(10, 6))
plt.bar(meses, y_futuro, color='#e74c3c', edgecolor='black')
plt.xlabel('Mês', fontsize=12)
plt.ylabel('Produção (t)', fontsize=12)
plt.title(f'Previsão de Produtividade - {ano_futuro}', fontsize=14, fontweight='bold')
for i, v in enumerate(y_futuro):
    plt.text(i, v + max(y_futuro)*0.02, f'{v:.1f}',
             ha='center', fontsize=9, fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('grafico_previsao.png', dpi=300)
plt.show()

print(" Gráfico salvo: 'grafico_previsao.png'")

print("\n Concluído!")